/**
 * @file stm32_example.c
 * @brief Example usage of MAVLink HAL on STM32 platform
 *
 * This example demonstrates how to use the portable MAVLink HAL
 * for UART communication on STM32 platforms.
 *
 * @author Auto-generated for Epic1 Task1
 * @date 2025-11-10
 */

#include "../include/mavlink_hal_interface.h"

/* STM32 HAL includes (generated by CubeMX) */
#include "main.h"
#include "usart.h"

/* ============================================================================
 * Example 1: Simple UART Communication
 * ============================================================================ */

void example_uart_basic(void)
{
    /* Configure UART for MAVLink communication */
    mavlink_hal_uart_config_t uart_config = {
        .baudrate = 115200,
        .data_bits = 8,
        .stop_bits = 1,
        .parity = 0,              /* No parity */
        .flow_control = false,
        .rx_buffer_size = 512,
        .tx_buffer_size = 512
    };

    /* Initialize UART through HAL (using CubeMX-generated handle) */
    extern UART_HandleTypeDef huart2;
    mavlink_hal_error_t err = g_mavlink_hal.uart_init(&huart2, &uart_config);

    if (err != MAVLINK_HAL_OK) {
        /* Handle error */
        while (1);  /* Error loop */
    }

    /* Send a test message */
    const uint8_t message[] = "Hello MAVLink HAL!\r\n";
    size_t bytes_sent;

    err = g_mavlink_hal.uart_send(
        &huart2,
        message,
        sizeof(message) - 1,
        1000,  /* 1 second timeout */
        &bytes_sent
    );

    if (err == MAVLINK_HAL_OK) {
        /* Message sent successfully */
    } else if (err == MAVLINK_HAL_ERR_TIMEOUT) {
        /* Timeout occurred */
    }
}

/* ============================================================================
 * Example 2: UART Receive with Timeout
 * ============================================================================ */

void example_uart_receive(void)
{
    extern UART_HandleTypeDef huart2;

    uint8_t rx_buffer[64];
    size_t bytes_received;

    /* Receive up to 64 bytes with 500ms timeout */
    mavlink_hal_error_t err = g_mavlink_hal.uart_receive(
        &huart2,
        rx_buffer,
        sizeof(rx_buffer),
        500,  /* 500ms timeout */
        &bytes_received
    );

    if (err == MAVLINK_HAL_OK) {
        /* Process received data */
        for (size_t i = 0; i < bytes_received; i++) {
            /* Handle each byte */
        }
    } else if (err == MAVLINK_HAL_ERR_TIMEOUT) {
        /* No data received within timeout */
    }
}

/* ============================================================================
 * Example 3: UART RX Callback (Interrupt-based)
 * ============================================================================ */

void uart_rx_callback(const uint8_t* data, size_t length, void* user_data)
{
    /* This callback is called when data is received */
    /* Note: Keep processing minimal - this runs in interrupt context */

    /* Example: Toggle LED on data reception */
    HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);

    /* Example: Forward data to processing queue */
    /* ... */
}

void example_uart_callback(void)
{
    extern UART_HandleTypeDef huart2;

    /* Register RX callback */
    int context_id = 42;  /* User-defined context */

    mavlink_hal_error_t err = g_mavlink_hal.uart_register_rx_callback(
        &huart2,
        uart_rx_callback,
        &context_id
    );

    if (err == MAVLINK_HAL_OK) {
        /* Callback registered - will be called on RX interrupt */
    }
}

/* ============================================================================
 * Example 4: Using Timers
 * ============================================================================ */

void example_timers(void)
{
    /* Get current time in milliseconds */
    uint32_t start_time = g_mavlink_hal.time_millis();

    /* Perform some operation */
    g_mavlink_hal.delay_ms(100);  /* Delay 100ms */

    /* Calculate elapsed time */
    uint32_t elapsed = g_mavlink_hal.time_millis() - start_time;

    /* Microsecond precision timing */
    uint64_t start_us = g_mavlink_hal.time_micros();
    g_mavlink_hal.delay_us(50);  /* Delay 50 microseconds */
    uint64_t elapsed_us = g_mavlink_hal.time_micros() - start_us;
}

/* ============================================================================
 * Example 5: Feature Detection
 * ============================================================================ */

void example_feature_detection(void)
{
    /* Check if HAL is initialized */
    if (!mavlink_hal_is_initialized()) {
        /* HAL not initialized */
        return;
    }

    /* Get platform name */
    const char* platform = mavlink_hal_get_platform_name();
    /* "STM32" on STM32 platforms */

    /* Check for specific features */
    if (mavlink_hal_has_feature(MAVLINK_HAL_FEATURE_UART)) {
        /* UART operations available */
    }

    if (mavlink_hal_has_feature(MAVLINK_HAL_FEATURE_CAN)) {
        /* CAN operations available */
    }

    if (mavlink_hal_has_feature(MAVLINK_HAL_FEATURE_PWM)) {
        /* PWM operations available */
    }
}

/* ============================================================================
 * Example 6: Error Handling
 * ============================================================================ */

void example_error_handling(void)
{
    extern UART_HandleTypeDef huart2;

    uint8_t tx_buffer[] = "Test";
    size_t bytes_sent;

    mavlink_hal_error_t err = g_mavlink_hal.uart_send(
        &huart2,
        tx_buffer,
        sizeof(tx_buffer),
        1000,
        &bytes_sent
    );

    /* Check for specific errors */
    switch (err) {
        case MAVLINK_HAL_OK:
            /* Success - check bytes_sent */
            break;

        case MAVLINK_HAL_ERR_TIMEOUT:
            /* Timeout - retry or handle */
            break;

        case MAVLINK_HAL_ERR_INVALID_PARAM:
            /* Invalid parameter - check inputs */
            break;

        case MAVLINK_HAL_ERR_HW_FAULT:
            /* Hardware fault - reinitialize */
            break;

        default:
            /* Other error */
            break;
    }

    /* Alternative: Simple success check */
    if (MAVLINK_HAL_IS_OK(err)) {
        /* Operation succeeded */
    } else {
        /* Operation failed */
    }
}

/* ============================================================================
 * Example 7: Integration with MAVLink Message Sending
 * ============================================================================ */

#include "mavlink/common/mavlink.h"  /* If MAVLink library is available */

void example_mavlink_integration(void)
{
    extern UART_HandleTypeDef huart2;

    /* Create a MAVLink message (example: heartbeat) */
    mavlink_message_t msg;
    uint8_t buf[MAVLINK_MAX_PACKET_LEN];

    mavlink_msg_heartbeat_pack(
        1,     /* System ID */
        1,     /* Component ID */
        &msg,
        MAV_TYPE_ONBOARD_CONTROLLER,
        MAV_AUTOPILOT_INVALID,
        0, 0, 0
    );

    /* Serialize message to buffer */
    uint16_t len = mavlink_msg_to_send_buffer(buf, &msg);

    /* Send via portable HAL */
    size_t bytes_sent;
    mavlink_hal_error_t err = g_mavlink_hal.uart_send(
        &huart2,
        buf,
        len,
        1000,
        &bytes_sent
    );

    if (err == MAVLINK_HAL_OK && bytes_sent == len) {
        /* MAVLink message sent successfully */
    }
}

/* ============================================================================
 * Example 8: Validation
 * ============================================================================ */

void example_validation(void)
{
    /* Validate that all required HAL functions are implemented */
    mavlink_hal_error_t err = mavlink_hal_validate();

    if (err == MAVLINK_HAL_OK) {
        /* All required functions present */
        /* Safe to use HAL */
    } else {
        /* Missing required functions */
        /* Cannot use HAL reliably */
        while (1);  /* Error loop */
    }
}

/* ============================================================================
 * Main Example - Typical Usage Pattern
 * ============================================================================ */

void mavlink_hal_example_main(void)
{
    /* 1. Validate HAL */
    if (mavlink_hal_validate() != MAVLINK_HAL_OK) {
        /* HAL not properly initialized */
        while (1);
    }

    /* 2. Configure UART */
    extern UART_HandleTypeDef huart2;

    mavlink_hal_uart_config_t uart_config = {
        .baudrate = 115200,
        .data_bits = 8,
        .stop_bits = 1,
        .parity = 0,
        .flow_control = false,
        .rx_buffer_size = 512,
        .tx_buffer_size = 512
    };

    if (g_mavlink_hal.uart_init(&huart2, &uart_config) != MAVLINK_HAL_OK) {
        /* UART init failed */
        while (1);
    }

    /* 3. Main loop */
    uint8_t rx_buffer[128];
    size_t bytes_received;

    while (1) {
        /* Non-blocking receive with short timeout */
        mavlink_hal_error_t err = g_mavlink_hal.uart_receive(
            &huart2,
            rx_buffer,
            sizeof(rx_buffer),
            10,  /* 10ms timeout */
            &bytes_received
        );

        if (err == MAVLINK_HAL_OK && bytes_received > 0) {
            /* Process received MAVLink data */
            /* ... */
        }

        /* Send periodic heartbeat every 1 second */
        static uint32_t last_heartbeat = 0;
        uint32_t now = g_mavlink_hal.time_millis();

        if (now - last_heartbeat >= 1000) {
            /* Send heartbeat */
            const uint8_t heartbeat_msg[] = "HEARTBEAT\r\n";
            size_t bytes_sent;

            g_mavlink_hal.uart_send(
                &huart2,
                heartbeat_msg,
                sizeof(heartbeat_msg) - 1,
                100,
                &bytes_sent
            );

            last_heartbeat = now;
        }

        /* Small delay to prevent busy loop */
        g_mavlink_hal.delay_ms(1);
    }
}
